INSERT INTO PERSON(ID, USERNAME, PASSWORD, EMAIL) VALUES (1, 'John', 'test', 'john@pet.com');
INSERT INTO PERSON(ID, USERNAME, PASSWORD, EMAIL) VALUES (2, 'Mary', 'test', 'mary@pet.com');
INSERT INTO PERSON(ID, USERNAME, PASSWORD, EMAIL) VALUES (3, 'Victoria', 'test', 'victoria@pet.com');
INSERT INTO PERSON(ID, USERNAME, PASSWORD, EMAIL) VALUES (4, 'Johnny', 'test', 'johnny@pet.com');

INSERT INTO DETECTIVE(ID, PERSON_ID, BADGE_NUMBER, ARMED, STATUS) VALUES (1, 1, 'LD112233', FALSE, 'ACTIVE');
INSERT INTO DETECTIVE(ID, PERSON_ID, BADGE_NUMBER, ARMED, STATUS) VALUES (2, 2, 'EH113322', TRUE, 'ACTIVE');